[build]
  base    = ""
  command = "npm build"

[dev]
  targetPort = 3000
  port = 8888

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/pages/brands"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/pages/our-team"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/pages/our-studio-new"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/pages/our-story-new"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/pages/get-started-new"
  to = "/contact/"
  status = 301

[[redirects]]
  from = "/pages/cut-sew"
  to = "/services/cut-and-sew/"
  status = 301

[[redirects]]
  from = "/pages/screen-printing"
  to = "/services/screen-printing/"
  status = 301

[[redirects]]
  from = "/pages/accessories"
  to = "/services/accessories/"
  status = 301

[[redirects]]
  from = "/pages/services"
  to = "/services/"
  status = 301

[[redirects]]
  from = "/home/"
  to = "/"
  status = 301
