// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  landing_page_content_simple: dynamic(
    () => import("./LandingPageContentSimple"),
  ),
};
